# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.2"
manifest_format = "2.0"
project_hash = "d603fb3eee1b2277f12070898fa99882bd83b3b7"

[[deps.FunctionWrappers]]
git-tree-sha1 = "d62485945ce5ae9c0c48f124a84998d755bae00e"
uuid = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
version = "1.1.3"

[[deps.Jlr]]
path = "."
uuid = "0ea60dbf-1165-4e7e-8282-76d66728f146"
version = "0.1.0"
