name = "Jlr"
uuid = "0ea60dbf-1165-4e7e-8282-76d66728f146"
version = "0.1.0"
authors = ["ken-morel <engonken8@gmail.com>"]

[deps]
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
FunctionWrappers = "1.1.3"
Revise = "3.12.3"
